-------CREATE TABLE BOOKS
CREATE TABLE BOOKS(
    BOOK_ID INT PRIMARY KEY,
    TITLE VARCHAR(200),
    AUTHOR VARCHAR(100),
    GENRE VARCHAR(50),
    PUBLISHED_YEAR INT,
    PRICE NUMERIC(10,2),
    STOCK INT
);


--CREATE TABLE CUSTOMER
CREATE TABLE CUSTOMERS(
CUSTOMER_ID INT PRIMARY KEY,
NAME VARCHAR(100),
EMAIL VARCHAR(100),
PHONE VARCHAR(20),
CITY VARCHAR(100),
COUNTRY VARCHAR(100)
);

----CREATE TABLE ORDERS
CREATE TABLE ORDERS(
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    BOOK_ID INT,
    ORDER_DATE DATE,
    QUANTITY INT,
    TOTAL_AMOUNT NUMERIC(10,2),
	FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (BOOK_ID)
    REFERENCES BOOKS(BOOK_ID)
);


SELECT * FROM BOOKS;
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;

--IMPORT FROM CSV TO BOOKS
COPY BOOKS(BOOK_ID,TITLE,AUTHOR,GENRE,PUBLISHED_YEAR,PRICE,STOCK)
FROM 'D:\LEARN\posgresql\PROJECT\Books.csv'
DELIMITER ','
CSV HEADER;

---IMPORT FROM CSV TO CUSTOMER

COPY CUSTOMERS(CUSTOMER_ID,NAME,EMAIL,PHONE,CITY,COUNTRY)
FROM 'D:\LEARN\posgresql\PROJECT\Customers.csv'
DELIMITER ','
CSV HEADER;

----IMPORT ORDERS FROM CSV

COPY ORDERS(ORDER_ID,CUSTOMER_ID,BOOK_ID,ORDER_DATE,QUANTITY,TOTAL_AMOUNT)
FROM 'D:\LEARN\posgresql\PROJECT\Orders.csv'
DELIMITER ','
CSV HEADER;


---BASIC QUERIES

------BOOKS FROM FICTION GENRE

SELECT *
FROM BOOKS
WHERE GENRE='Fiction';

-----BOOKS PUBLISHED AFTER YEAR 1950
SELECT *
FROM BOOKS
WHERE PUBLISHED_YEAR>1950;


------LISTING ALL CUSTOMER FROM CANADA

SELECT *
FROM CUSTOMERS
WHERE COUNTRY='Canada';

----ORDER PLACED IN NOVEMBER 2023
SELECT *
FROM ORDERS
WHERE ORDER_DATE BETWEEN '2023-11-01' AND '2023-11-30';

----TOTAL STOCKS ACROSS ALL BOOK
SELECT SUM(STOCK)
FROM BOOKS;

-----MOST EXPENSIVE BOOK
SELECT *
FROM BOOKS
ORDER BY PRICE DESC
LIMIT 1;

--LEAST EXPENSIVE BOOK

SELECT *
FROM BOOKS
ORDER BY PRICE ASC
LIMIT 1;

-----BOOKS STOCK LESS THAN 10

SELECT *
FROM BOOKS
WHERE STOCK<10;

----DIFFERENT GENRE AVAILABLE
SELECT DISTINCT GENRE AS DIFFERENT_GENRE_AVAILABLE
FROM BOOKS;


---NUMBER OF BOOKS AVAILABLE IN DIFFERENT GENRE
SELECT GENRE,COUNT(*) AS BOOKSCOUNT
FROM BOOKS
GROUP BY GENRE;

----AVERAGE PRICE OF ALL BOOKS
SELECT AVG(PRICE) AS AVERAGE_PRICE
FROM BOOKS;

----TOTAL REVENUE FROM ALL BOOKS
SELECT SUM(TOTAL_AMOUNT)AS REVENUE
FROM ORDERS;

-----ADVANCED QUERIES

----TOTAL NUMBER OF BOOKS SOLD FOR EACH GENRE
SELECT GENRE,SUM(O.QUANTITY) AS TOTAL_SOLD
FROM ORDERS O
INNER JOIN 
BOOKS B
ON O.BOOK_ID=B.BOOK_ID
GROUP BY GENRE;

----AVERAGE PRICE OF BOOKS IN FANTASY GENRE
SELECT AVG(PRICE) AS AVERAGEPRICE
FROM BOOKS
WHERE GENRE='Fantasy';

----LIST OF CUSTOMER WHO HAVE PLACED ATLEAST 2 ORDERS
SELECT O.CUSTOMER_ID,C.NAME,COUNT(O.ORDER_ID)
FROM ORDERS O
INNER JOIN 
CUSTOMERS C
ON O.CUSTOMER_ID=C.CUSTOMER_ID
GROUP BY O.CUSTOMER_ID,C.NAME
HAVING COUNT(ORDER_ID)>=2;

------MOST FREQUENTLY ORDERED BOOK
SELECT B.TITLE,O.BOOK_ID,COUNT(O.ORDER_ID) AS ORDERED
FROM ORDERS O
INNER JOIN 
BOOKS B
ON O.BOOK_ID=B.BOOK_ID
GROUP BY O.BOOK_ID,B.TITLE
ORDER BY COUNT(O.ORDER_ID) DESC
limit 1;

----TOP 3 MOST EXPENSIVE BOOK FOR FANTASY GENRE
SELECT * 
FROM BOOKS
WHERE GENRE='Fantasy'
ORDER BY PRICE DESC
LIMIT 3;

----TOTAL QUANTITY SOLD BY EACH AUTHOR

SELECT B.AUTHOR,SUM(QUANTITY) AS TOTAL_QUANTITY
FROM ORDERS O
INNER JOIN
BOOKS B
ON O.BOOK_ID=B.BOOK_ID
GROUP BY B.AUTHOR;

----LIST THE CITY CUSTOMERS SPENT MORE THAN $30
SELECT  DISTINCT C.CITY,SUM(O.TOTAL_AMOUNT)
FROM ORDERS O
JOIN 
CUSTOMERS C
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CITY
HAVING SUM(O.TOTAL_AMOUNT)>30; 

-----FIND THE CUSTOMER WHO SPENT MOST ON ORDERS
SELECT C.NAME,SUM(O.TOTAL_AMOUNT) AS SPENT
FROM ORDERS O
JOIN
CUSTOMERS C
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.NAME

ORDER BY SUM(O.TOTAL_AMOUNT) DESC
LIMIT 1;

---STOCK REMAINING AFTER FULFILLING ALL ORDER

SELECT B.TITLE,B.STOCK,COALESCE(SUM(O.QUANTITY),0) AS BOOKS_ORDERED_QUANTITY,B.STOCK-COALESCE(SUM(O.QUANTITY),0) AS QUANTITYREMAINING
FROM BOOKS B
LEFT JOIN
ORDERS O
ON O.BOOK_ID=B.BOOK_ID
GROUP BY B.BOOK_ID
ORDER BY B.BOOK_ID ASC;





